require "test_helper"
# THIS FILE IS AUTOGENERATED FROM trailblazer-activity-dsl-linear/test/docs/wiring_api_test.rb

class WiringApiDocsTest < Minitest::Spec
# {#terminus} 1.0
  module A
    class Payment
      module Operation
      end
    end

    #:terminus
    module Payment::Operation
      class Create < Trailblazer::Operation
        step :find_provider

        terminus :provider_invalid # , id: "End.provider_invalid", magnetic_to: :provider_invalid
        #~meths
        include T.def_steps(:find_provider)
        #~meths end
      end
    end
    #:terminus end
    # @diagram wiring-terminus
  end

  #@ we cannot route to {End.provider_invalid}
  it { assert_invoke A::Payment::Operation::Create, seq: "[:find_provider]" }
  it { assert_invoke A::Payment::Operation::Create, find_provider: false, seq: "[:find_provider]", terminus: :failure }

# {#terminus} 1.1
  module B
    class Payment
      module Operation
      end
    end

    #:terminus-track
    module Payment::Operation
      class Create < Trailblazer::Operation
        step :find_provider,
          # connect {failure} to the next element that is magnetic_to {:provider_invalid}.
          Output(:failure) => Track(:provider_invalid)

        terminus :provider_invalid
        #~meths
        include T.def_steps(:find_provider)
        #~meths end
      end
    end
    #:terminus-track end
  end

  #@ failure routes to {End.provider_invalid}
  it { assert_invoke B::Payment::Operation::Create, seq: "[:find_provider]" }
  it { assert_invoke B::Payment::Operation::Create, find_provider: false, seq: "[:find_provider]", terminus: :provider_invalid }

  it do
    result = B::Payment::Operation::Create.(find_provider: false, seq: [])
    assert_equal result.event.to_h[:semantic], :provider_invalid
=begin
    #:terminus-invalid
    result = Payment::Operation::Create.(provider: "bla-unknown")
    puts signal.to_h[:semantic] #=> :provider_invalid
    #:terminus-invalid end
=end

  end
end

#@ :magnetic_to
module A
  class MagneticTo_DocsTest < Minitest::Spec
    Memo = Class.new
    #:magnetic_to
    module Memo::Operation
      class Create < Trailblazer::Operation
        step :validate
        step :payment_provider, Output(:failure) => Track(:paypal)
        step :charge_paypal, magnetic_to: :paypal
        step :save
      end
    end
    #:magnetic_to end

    it "what" do
#~ignore end
    end

  end
end
